from __future__ import annotations

ALLOWED_INDICATORS = {"close", "open", "high", "low", "volume", "sma", "ema", "rsi"}
ALLOWED_OPS = {"above", "below"}
ALLOWED_JOIN = {"AND", "OR"}
DEFAULT_MA_PERIOD = 20
DEFAULT_RSI_PERIOD = 14


class StrategyBuilder:
    def generate(self, spec: dict) -> str:
        errors = self.validate(spec)
        if errors:
            raise ValueError("; ".join(errors))
        entry = spec.get("entry") or {}
        exit_rule = spec.get("exit") or {}
        entry_expr = self._rule_expr(entry)
        exit_expr = self._rule_expr(exit_rule) if exit_rule.get("conditions") else None
        rsi_blocks = self._rsi_blocks(spec)
        return self._render(entry_expr, exit_expr, rsi_blocks)

    def validate(self, spec: dict) -> list[str]:
        errors: list[str] = []
        entry = spec.get("entry") or {}
        exit_rule = spec.get("exit") or {}
        if not entry.get("conditions") and not exit_rule.get("conditions"):
            errors.append("at least one condition needed (entry or exit)")
        errors.extend(self._rule_errors(entry, "entry"))
        errors.extend(self._rule_errors(exit_rule, "exit"))
        return errors

    def _rule_errors(self, rule: dict, path: str) -> list[str]:
        errors: list[str] = []
        op = rule.get("op")
        if op is not None and op not in ALLOWED_JOIN:
            errors.append(f"{path}.op must be AND or OR")
        for i, cond in enumerate(rule.get("conditions") or []):
            errors.extend(self._condition_errors(cond, f"{path}.conditions[{i}]"))
        return errors

    def _condition_errors(self, cond: dict, path: str) -> list[str]:
        errors: list[str] = []
        ind = cond.get("indicator")
        if ind not in ALLOWED_INDICATORS:
            errors.append(f"{path}.indicator must be one of {sorted(ALLOWED_INDICATORS)}")
        op = cond.get("op")
        if op not in ALLOWED_OPS:
            errors.append(f"{path}.op must be above or below")
        if "ref" in cond and cond["ref"] is not None:
            if cond["ref"] not in ALLOWED_INDICATORS:
                errors.append(f"{path}.ref must be one of {sorted(ALLOWED_INDICATORS)}")
        elif not isinstance(cond.get("value"), (int, float)):
            errors.append(f"{path}.value must be a number")
        return errors

    def _rule_expr(self, rule: dict) -> str:
        parts = [self._condition_expr(c) for c in rule.get("conditions") or []]
        if not parts:
            return "True"
        joiner = " & " if rule.get("op", "AND") == "AND" else " | "
        return "(" + joiner.join(parts) + ")"

    def _condition_expr(self, cond: dict) -> str:
        left = self._series_expr(cond.get("indicator", "close"), cond.get("period"))
        op = cond.get("op", "above")
        cmp = ">" if op == "above" else "<"
        if "ref" in cond and cond["ref"] is not None:
            right = self._series_expr(cond["ref"], cond.get("ref_period"))
            return f"({left} {cmp} {right})"
        return f"({left} {cmp} {float(cond['value'])!r})"

    @staticmethod
    def _series_expr(indicator: str, period) -> str:
        if indicator == "rsi":
            return f"rsi_{int(period or DEFAULT_RSI_PERIOD)}"
        if indicator == "sma":
            return f'data["close"].rolling({int(period or DEFAULT_MA_PERIOD)}).mean()'
        if indicator == "ema":
            return f'data["close"].ewm(span={int(period or DEFAULT_MA_PERIOD)}, adjust=False).mean()'
        return f'data["{indicator}"]'

    @staticmethod
    def _rsi_blocks(spec: dict) -> list[str]:
        periods: set[int] = set()

        def collect(rule: dict) -> None:
            for cond in rule.get("conditions") or []:
                if cond.get("indicator") == "rsi":
                    periods.add(int(cond.get("period") or DEFAULT_RSI_PERIOD))
                if "ref" in cond and cond.get("ref") == "rsi":
                    periods.add(int(cond.get("ref_period") or DEFAULT_RSI_PERIOD))

        collect(spec.get("entry") or {})
        collect(spec.get("exit") or {})
        blocks = []
        for period in sorted(periods):
            blocks.extend(
                [
                    f'delta = data["close"].diff()',
                    "gain = delta.clip(lower=0)",
                    "loss = -delta.clip(upper=0)",
                    f"avg_gain = gain.ewm(alpha=1/{period}, adjust=False).mean()",
                    f"avg_loss = loss.ewm(alpha=1/{period}, adjust=False).mean()",
                    "rs = avg_gain / avg_loss",
                    "rs = rs.where(avg_loss != 0, 100.0)",
                    f"rsi_{period} = 100 - 100 / (1 + rs)",
                ]
            )
        return blocks

    @staticmethod
    def _render(entry_expr: str, exit_expr: str | None, rsi_blocks: list[str]) -> str:
        lines = ["# generated by StrategyBuilder"]
        lines.extend(rsi_blocks)
        lines.append(f"entry = {entry_expr}")
        lines.append(f"exit = ~entry" if exit_expr is None else f"exit = {exit_expr}")
        lines.extend(
            [
                "in_market = 0",
                "out = []",
                "for i in range(len(data)):",
                "    if in_market == 0 and bool(entry.iloc[i]):",
                "        in_market = 1",
                "    elif in_market == 1 and bool(exit.iloc[i]):",
                "        in_market = 0",
                "    out.append(1 if in_market else -1)",
                "signals = pd.Series(out, index=data.index)",
                "",
            ]
        )
        return "\n".join(lines)
